// lib/phone-dial-codes.ts
//
// Static map: ISO-2 country code → international dial code.
// Flag emoji is derived from the ISO-2 code (no bundled SVG sprites).
// Source: ITU-T E.164, ISO 3166-1 alpha-2. Covers 240+ territories.

export interface DialEntry {
  code: string; // ISO-2
  dial: string; // +90 (primary dial code; some territories have multiple)
}

// Primary dial codes only. For territories sharing codes (e.g. CA/US: +1),
// each has its own row so flag + label stay correct in the UI.
export const DIAL_CODES: readonly DialEntry[] = [
  { code: "AF", dial: "+93" },
  { code: "AL", dial: "+355" },
  { code: "DZ", dial: "+213" },
  { code: "AS", dial: "+1684" },
  { code: "AD", dial: "+376" },
  { code: "AO", dial: "+244" },
  { code: "AI", dial: "+1264" },
  { code: "AG", dial: "+1268" },
  { code: "AR", dial: "+54" },
  { code: "AM", dial: "+374" },
  { code: "AW", dial: "+297" },
  { code: "AU", dial: "+61" },
  { code: "AT", dial: "+43" },
  { code: "AZ", dial: "+994" },
  { code: "BS", dial: "+1242" },
  { code: "BH", dial: "+973" },
  { code: "BD", dial: "+880" },
  { code: "BB", dial: "+1246" },
  { code: "BY", dial: "+375" },
  { code: "BE", dial: "+32" },
  { code: "BZ", dial: "+501" },
  { code: "BJ", dial: "+229" },
  { code: "BM", dial: "+1441" },
  { code: "BT", dial: "+975" },
  { code: "BO", dial: "+591" },
  { code: "BA", dial: "+387" },
  { code: "BW", dial: "+267" },
  { code: "BR", dial: "+55" },
  { code: "IO", dial: "+246" },
  { code: "VG", dial: "+1284" },
  { code: "BN", dial: "+673" },
  { code: "BG", dial: "+359" },
  { code: "BF", dial: "+226" },
  { code: "BI", dial: "+257" },
  { code: "KH", dial: "+855" },
  { code: "CM", dial: "+237" },
  { code: "CA", dial: "+1" },
  { code: "CV", dial: "+238" },
  { code: "KY", dial: "+1345" },
  { code: "CF", dial: "+236" },
  { code: "TD", dial: "+235" },
  { code: "CL", dial: "+56" },
  { code: "CN", dial: "+86" },
  { code: "CX", dial: "+61" },
  { code: "CC", dial: "+61" },
  { code: "CO", dial: "+57" },
  { code: "KM", dial: "+269" },
  { code: "CD", dial: "+243" },
  { code: "CG", dial: "+242" },
  { code: "CK", dial: "+682" },
  { code: "CR", dial: "+506" },
  { code: "HR", dial: "+385" },
  { code: "CU", dial: "+53" },
  { code: "CW", dial: "+599" },
  { code: "CY", dial: "+357" },
  { code: "CZ", dial: "+420" },
  { code: "CI", dial: "+225" },
  { code: "DK", dial: "+45" },
  { code: "DJ", dial: "+253" },
  { code: "DM", dial: "+1767" },
  { code: "DO", dial: "+1809" },
  { code: "EC", dial: "+593" },
  { code: "EG", dial: "+20" },
  { code: "SV", dial: "+503" },
  { code: "GQ", dial: "+240" },
  { code: "ER", dial: "+291" },
  { code: "EE", dial: "+372" },
  { code: "SZ", dial: "+268" },
  { code: "ET", dial: "+251" },
  { code: "FK", dial: "+500" },
  { code: "FO", dial: "+298" },
  { code: "FJ", dial: "+679" },
  { code: "FI", dial: "+358" },
  { code: "FR", dial: "+33" },
  { code: "GF", dial: "+594" },
  { code: "PF", dial: "+689" },
  { code: "GA", dial: "+241" },
  { code: "GM", dial: "+220" },
  { code: "GE", dial: "+995" },
  { code: "DE", dial: "+49" },
  { code: "GH", dial: "+233" },
  { code: "GI", dial: "+350" },
  { code: "GR", dial: "+30" },
  { code: "GL", dial: "+299" },
  { code: "GD", dial: "+1473" },
  { code: "GP", dial: "+590" },
  { code: "GU", dial: "+1671" },
  { code: "GT", dial: "+502" },
  { code: "GG", dial: "+44" },
  { code: "GN", dial: "+224" },
  { code: "GW", dial: "+245" },
  { code: "GY", dial: "+592" },
  { code: "HT", dial: "+509" },
  { code: "HN", dial: "+504" },
  { code: "HK", dial: "+852" },
  { code: "HU", dial: "+36" },
  { code: "IS", dial: "+354" },
  { code: "IN", dial: "+91" },
  { code: "ID", dial: "+62" },
  { code: "IR", dial: "+98" },
  { code: "IQ", dial: "+964" },
  { code: "IE", dial: "+353" },
  { code: "IM", dial: "+44" },
  { code: "IL", dial: "+972" },
  { code: "IT", dial: "+39" },
  { code: "JM", dial: "+1876" },
  { code: "JP", dial: "+81" },
  { code: "JE", dial: "+44" },
  { code: "JO", dial: "+962" },
  { code: "KZ", dial: "+7" },
  { code: "KE", dial: "+254" },
  { code: "KI", dial: "+686" },
  { code: "XK", dial: "+383" },
  { code: "KW", dial: "+965" },
  { code: "KG", dial: "+996" },
  { code: "LA", dial: "+856" },
  { code: "LV", dial: "+371" },
  { code: "LB", dial: "+961" },
  { code: "LS", dial: "+266" },
  { code: "LR", dial: "+231" },
  { code: "LY", dial: "+218" },
  { code: "LI", dial: "+423" },
  { code: "LT", dial: "+370" },
  { code: "LU", dial: "+352" },
  { code: "MO", dial: "+853" },
  { code: "MG", dial: "+261" },
  { code: "MW", dial: "+265" },
  { code: "MY", dial: "+60" },
  { code: "MV", dial: "+960" },
  { code: "ML", dial: "+223" },
  { code: "MT", dial: "+356" },
  { code: "MH", dial: "+692" },
  { code: "MQ", dial: "+596" },
  { code: "MR", dial: "+222" },
  { code: "MU", dial: "+230" },
  { code: "YT", dial: "+262" },
  { code: "MX", dial: "+52" },
  { code: "FM", dial: "+691" },
  { code: "MD", dial: "+373" },
  { code: "MC", dial: "+377" },
  { code: "MN", dial: "+976" },
  { code: "ME", dial: "+382" },
  { code: "MS", dial: "+1664" },
  { code: "MA", dial: "+212" },
  { code: "MZ", dial: "+258" },
  { code: "MM", dial: "+95" },
  { code: "NA", dial: "+264" },
  { code: "NR", dial: "+674" },
  { code: "NP", dial: "+977" },
  { code: "NL", dial: "+31" },
  { code: "NC", dial: "+687" },
  { code: "NZ", dial: "+64" },
  { code: "NI", dial: "+505" },
  { code: "NE", dial: "+227" },
  { code: "NG", dial: "+234" },
  { code: "NU", dial: "+683" },
  { code: "KP", dial: "+850" },
  { code: "MK", dial: "+389" },
  { code: "NO", dial: "+47" },
  { code: "OM", dial: "+968" },
  { code: "PK", dial: "+92" },
  { code: "PW", dial: "+680" },
  { code: "PS", dial: "+970" },
  { code: "PA", dial: "+507" },
  { code: "PG", dial: "+675" },
  { code: "PY", dial: "+595" },
  { code: "PE", dial: "+51" },
  { code: "PH", dial: "+63" },
  { code: "PL", dial: "+48" },
  { code: "PT", dial: "+351" },
  { code: "PR", dial: "+1787" },
  { code: "QA", dial: "+974" },
  { code: "RO", dial: "+40" },
  { code: "RU", dial: "+7" },
  { code: "RW", dial: "+250" },
  { code: "RE", dial: "+262" },
  { code: "BL", dial: "+590" },
  { code: "SH", dial: "+290" },
  { code: "KN", dial: "+1869" },
  { code: "LC", dial: "+1758" },
  { code: "MF", dial: "+590" },
  { code: "PM", dial: "+508" },
  { code: "VC", dial: "+1784" },
  { code: "WS", dial: "+685" },
  { code: "SM", dial: "+378" },
  { code: "ST", dial: "+239" },
  { code: "SA", dial: "+966" },
  { code: "SN", dial: "+221" },
  { code: "RS", dial: "+381" },
  { code: "SC", dial: "+248" },
  { code: "SL", dial: "+232" },
  { code: "SG", dial: "+65" },
  { code: "SX", dial: "+1721" },
  { code: "SK", dial: "+421" },
  { code: "SI", dial: "+386" },
  { code: "SB", dial: "+677" },
  { code: "SO", dial: "+252" },
  { code: "ZA", dial: "+27" },
  { code: "KR", dial: "+82" },
  { code: "SS", dial: "+211" },
  { code: "ES", dial: "+34" },
  { code: "LK", dial: "+94" },
  { code: "SD", dial: "+249" },
  { code: "SR", dial: "+597" },
  { code: "SE", dial: "+46" },
  { code: "CH", dial: "+41" },
  { code: "SY", dial: "+963" },
  { code: "TW", dial: "+886" },
  { code: "TJ", dial: "+992" },
  { code: "TZ", dial: "+255" },
  { code: "TH", dial: "+66" },
  { code: "TL", dial: "+670" },
  { code: "TG", dial: "+228" },
  { code: "TK", dial: "+690" },
  { code: "TO", dial: "+676" },
  { code: "TT", dial: "+1868" },
  { code: "TN", dial: "+216" },
  { code: "TR", dial: "+90" },
  { code: "TM", dial: "+993" },
  { code: "TC", dial: "+1649" },
  { code: "TV", dial: "+688" },
  { code: "UG", dial: "+256" },
  { code: "UA", dial: "+380" },
  { code: "AE", dial: "+971" },
  { code: "GB", dial: "+44" },
  { code: "US", dial: "+1" },
  { code: "UY", dial: "+598" },
  { code: "UZ", dial: "+998" },
  { code: "VU", dial: "+678" },
  { code: "VA", dial: "+379" },
  { code: "VE", dial: "+58" },
  { code: "VN", dial: "+84" },
  { code: "WF", dial: "+681" },
  { code: "EH", dial: "+212" },
  { code: "YE", dial: "+967" },
  { code: "ZM", dial: "+260" },
  { code: "ZW", dial: "+263" },
];

const DIAL_BY_CODE = new Map<string, string>(DIAL_CODES.map((e) => [e.code, e.dial] as const));

/**
 * Look up international dial code by ISO-2 country code.
 * Returns null if the code is not in the map.
 */
export function getDialCode(iso2: string): string | null {
  return DIAL_BY_CODE.get(iso2.toUpperCase()) ?? null;
}

/**
 * Derive Unicode flag emoji from ISO-2 country code.
 * Uses regional indicator symbols (U+1F1E6..U+1F1FF).
 * Example: "TR" → "🇹🇷"
 */
export function flagEmoji(iso2: string): string {
  const upper = iso2.toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return "🏳";
  const A = 0x1f1e6;
  return (
    String.fromCodePoint(A + upper.charCodeAt(0) - 65) +
    String.fromCodePoint(A + upper.charCodeAt(1) - 65)
  );
}
